# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: change.me
ip: 192.168.33.100-changme

#
# WordPress Settings
#
version: latest
lang: en_US
title: CHANGE ME
multisite: false
rewrite_structure: /%postname%/

memory: 2048
#
# WordPress Path
#
wp_siteurl: ''  # Path to the WP_SITEURL like "wp"
wp_home: ''     # Path to the WP_HOME like "wp"

#
# WordPress User
#
admin_user: developer
admin_pass: developer
admin_email: vccw@example.com

##
## WordPress Database
##
db_prefix: wp_
db_host: localhost
db_name: wordpress
db_user: developer
db_pass: developer

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins:
  - debug-bar

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: ''

#
# WordPress Options
#
options: {}

#
# WordPress Multisite Options
#
multisite_options: {}

#
# The values of wp-config.php
#
force_ssl_admin: false
wp_debug: false
savequeries: false

#
# Addtional PHP code in the wp-config.php
#
extra_wp_config: |
  // Addtional PHP code in the wp-config.php
  // These lines are inserted by VCCW.
  // You can place addtional PHP code here!

#
# Theme unit testing
#
theme_unit_test: false
theme_unit_test_uri: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
# theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

#
# RubyGems
#
ruby_gems:
  - bundler
  - wordmove

#
# NPM modules
#
npms: []

#
# composer
#
composers:
  - hirak/prestissimo:*
  - phpunit/phpunit:*
  - squizlabs/php_codesniffer:*
  - wp-coding-standards/wpcs:*
  # - phpmd/phpmd:*
  # - sebastian/phpcpd:*
  # - phploc/phploc:*
  # - phing/phing:*

#
# wp-cli package commands
#
wp_cli_packages:
  - vccw/wp-cli-scaffold-movefile:@stable
